### ISSUE TITLE
The NFT Store let me buy an NFT 3 times but it didn't remember I bought it the 1st time

### ISSUE THREAD

**Issue by paulpoco** [signum-nft/feedback#1]
**Describe the bug**
The NFT Store let me buy an NFT 3 times but it didn't remember I bought it the 1st time

**To Reproduce**
1. Go to ['...'](https://signum-art-git-development-signum-network.vercel.app/item/16475828890872746155)
2. Click on '....' Buy NFT
3.  Click Buy NFT 2 more times

**Expected behavior**
Not allow me to buy 2 additional times
It did refund the additional 2 times

**Screenshots**
![image](https://user-images.githubusercontent.com/801414/154609114-77c12d7b-6592-498e-97a5-d0b2050c444b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 97

**Additional context**

**Comment by ohager** [comment]
@frankTheTank72 I told you :grin:

**Comment by Nivok-Spilkommen** [comment]
I'm used to this behavior, it is exactly the same when buying NFTs on the HIVE network.

**Comment by paulpoco** [comment]
User error
