### ISSUE TITLE
Commonness issue

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#11]
I think Commonness count incorrect. I made just 1 NFT with 3 attributes, so Commonness must be 100% for each attributes. 
If I create another NFT with the same attributes, Commonness  still must be 100%. But if I change only 1 attribute for second NFT - commonness should be 50% for it.

![image](https://user-images.githubusercontent.com/77928665/154749683-c04db5e5-bf01-4fef-9df4-f0bde24a27a4.png)

Here my example how it must work:
![image](https://user-images.githubusercontent.com/77928665/154749742-e7aed354-a08e-4374-8299-8975090fa1bf.png)

**Comment by rever273** [comment]
Plus the user cannot write the same attribute twice. There cannot be two "Background". The attributes reveal the rarity. It is very important for large collections.

**Comment by rever273** [comment]
And another problem:
![image](https://user-images.githubusercontent.com/77928665/163812194-0512809d-eeef-4bd5-af69-928eb2fd9621.png)

Automatically you have made it so that the user cannot specify letters in upper case, otherwise they are automatically changed to lower case. When writing the attributes, I used upper case twice (it changed to lower case) and once lower case. As a result, you can see that only the word "hell" remains in lower case, while the first two attributes are capitalized.

**Comment by frankTheTank72** [comment]
We solved it right now - please check
![grafik](https://user-images.githubusercontent.com/39116221/163863652-12f74066-60c4-4342-a859-d13f54741897.png)

and if okay close the ticket please

**Comment by rever273** [comment]
> 

Yes, everything OK now.
![image](https://user-images.githubusercontent.com/77928665/163898986-1ba3d511-1af6-47e9-b3ac-14c576a2de5c.png)

**Comment by frankTheTank72** [comment]
thx
