### ISSUE TITLE
Wrong owners counter

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#12]
My collection has 4 NFTs now and 2 owners: me and buyer. 
https://signum-art-git-development-signum-network.vercel.app/collection/13032391143528719091

But owners counter shows that it has only one owner
![image](https://user-images.githubusercontent.com/77928665/154763219-707e73d8-22b6-41f0-a788-02467eabc886.png)

**Comment by frankTheTank72** [comment]
Hi - we just count different owners - so **itsSpyTV** bought 2 of your NFTs .. this is only one unique owner ...
The number of owners should show how distributed the collection is..

**Comment by rever273** [comment]
But I'm the owner, too. Why is the number not 2? Owner and Creator

**Comment by frankTheTank72** [comment]
yes good point  - will take it up

**Comment by frankTheTank72** [comment]
fixed - pls check

**Comment by rever273** [comment]
@frankTheTank72 yes, great. Work correct.
