### ISSUE TITLE
Royalty issue

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#13]
I found another small issue. I sell my NFT first time but the table shows that I already get royalty. This is incorrect. First sale from owner always without royalty.
![image](https://user-images.githubusercontent.com/77928665/154770004-3807e540-6ee4-4b2b-82da-22be66175124.png)

**Comment by frankTheTank72** [comment]
We pay for simplification always royalty - if the first time the NFT is sold the whole amount goes to the creator - price including the royality  - it is technical the same
