### ISSUE TITLE
Missing shadow at "Platform Fee" section

### ISSUE THREAD

**Issue by shefass** [signum-nft/feedback#14]
**Describe the bug**
Missing shadow at "Platform Fee" section

**To Reproduce**
1. Go to ['...'](https://signum-art-git-development-signum-network.vercel.app/item/10949999814612525494)

**Expected behavior**
All elements with shadow 

**Screenshots**
![image](https://user-images.githubusercontent.com/39196313/154793565-b5f33b0e-673c-4e8f-ba72-f605fa1fca35.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu latest
 - Browser FireFox
 - Version latest

**Comment by frankTheTank72** [comment]
done please check @shefass  - and close the ticket if okay - thx
