### ISSUE TITLE
New Items don't update NFT

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#15]
11 hours ago was created last NFT, but New Items didn't change at all.
I suppose this section should update any time users add new NFT.

![image](https://user-images.githubusercontent.com/77928665/154796406-857bb907-d4e1-4ce3-8f47-0fb388a3b6b9.png)

**Comment by frankTheTank72** [comment]
we check this

**Comment by ohager** [comment]
The old rule was based on bids, but is being changed (and much more simplified) - mind, that only verified artists will be considered - this is to avoid spamming

**Comment by frankTheTank72** [comment]
we are just checking it again

**Comment by frankTheTank72** [comment]
should be solved now - pls check and close the ticjket if okay for you

**Comment by rever273** [comment]
It's not working.
![image](https://user-images.githubusercontent.com/77928665/155390601-1629a4df-d9a1-4cd7-b0d5-0557b595e0a8.png)

Here the last NFT created 5-6 days ago. 
There are newer nfts on the marketplace.
As I understand it, this section should display the most recent nfts that have been added by verified authors. In order from left to right.

**Comment by rever273** [comment]
Just added new NFT - https://signum-art-git-development-signum-network.vercel.app/de/item/13988462222708966034
It should be tht first in the list, but it's not. New items shows randomly.

**Comment by frankTheTank72** [comment]
yes we chnaged that to more randomness
