### ISSUE TITLE
Add volume to collection description

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#17]
On Solanart every collection has volume info on it. I think this is quite good decision.
![image](https://user-images.githubusercontent.com/77928665/154796624-9949ebf6-5e66-4a4e-95f6-5ed1ce0558aa.png)

Can you add something like this for each collection?:
![image](https://user-images.githubusercontent.com/77928665/154796757-af6b84c2-e268-48c8-acbf-32b4d938602e.png)

**Comment by frankTheTank72** [comment]
Like it - this we will do - 100%

**Comment by frankTheTank72** [comment]
added volume to top creators:
![grafik](https://user-images.githubusercontent.com/39116221/155031434-3a7b40ab-51b6-443a-9a0d-e3c3be3f25c8.png)

**Comment by frankTheTank72** [comment]
done on collection aslso - please check

**Comment by rever273** [comment]
Yes, looks good.

Last question here, what do you think about this design? It get 4 likes on discord.
![image](https://user-images.githubusercontent.com/77928665/155689214-ec693272-31c8-41c1-8fa5-47df8ccadfc7.png)

**Comment by frankTheTank72** [comment]
done -pls check

**Comment by rever273** [comment]
Ok, thx.
