### ISSUE TITLE
Hot collection top don't work

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#18]
Top Hot collection on main page shows incorrect rating.

![image](https://user-images.githubusercontent.com/77928665/154796822-17a8b469-f212-4ac4-94c3-5ecbaa310290.png)

First place take **BEARCOIN** with Ꞩ 1,020 volume. But **Logo Fantasy** and **Signuphant** collection have Ꞩ 5,500 and  Ꞩ 7,122 volume right now.

Also left and right allows unclickable.

**Comment by frankTheTank72** [comment]
The volume is one part - we also multiply it with the number of owners .. so the most distributed is first - max we show 10

**Comment by frankTheTank72** [comment]
I added some more artists as verfified

**Comment by frankTheTank72** [comment]
i think we can close that - please check on testnet
