### ISSUE TITLE
Add verify user's filter on explorer

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#19]
Now on Explore page we can see all NFT. I think if you want filter junk and give buyers option to choose, you need to add Author's verify filter like this: 

![image](https://user-images.githubusercontent.com/77928665/154809824-82224a53-1239-4026-ac6f-e7844598a0e8.png)

**Comment by frankTheTank72** [comment]
Yes that is in work

**Comment by frankTheTank72** [comment]
The story :

We should introdcue a new filter on the marketplace which filters onyl on verified artists
This filter should be activated by default.

Name : Artists
Values : "Verfied" or "All"

"Verfied" should be defalut, also when i reset the filters

**Comment by rever273** [comment]
I think "All" should be default. Otherwise not verified users never sell they art.

**Comment by frankTheTank72** [comment]
Or artists have an insentiv to verfiy by twitter ... i personal have a bad feeling if we promote NFTs from unknown source - this will give us a lot of noise on the portal

**Comment by rever273** [comment]
Well, OpenSea have no problem with it. Any user can add his collection and any user can report it.
Verification is needed for filters, but you can give the verify mark only manually.

You have to remember that many people, especially in Russia, don't have Twitter, we don't use it, it's not popular with us. So many artists will just create a new Twitter profile just to make an account on Signum Art. It doesn't mean that they are bad artists or that they are going to spread junk on the site.

Hot and feature collection should display only verified users. But expore should by default show all NFTs at all. Otherwise people will have no incentive to use the site. This can be changed as the marketplace develops.

**Comment by frankTheTank72** [comment]
we will consider your feedback - thx a lot
