### ISSUE TITLE
Profile Pics do not save

### ISSUE THREAD

**Issue by paulpoco** [signum-nft/feedback#2]
**Describe the bug**
Select Profile image and Profile banner, they show up on the same profile page.
Hit save changes below.
Go elsewhere on portal
Come back to profile section everything is there except Pics on profile

**Comment by paulpoco** [comment]
OK the Profile Pic showed up.

Just not Banner.   Re saved Banner again to see what will happen

**Comment by paulpoco** [comment]
Profile Banner didn't show up

**Comment by paulpoco** [comment]
Ok Banner finally showed up.

Do I close this?

Still a little confusing as the PNG uploaded files you do not really know if they have been saved until way later

**Comment by frankTheTank72** [comment]
i close this as #3 is the same
