### ISSUE TITLE
Add Explorer button to header 

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#20]
This is important button for buyers and they need to see it whole time:
![image](https://user-images.githubusercontent.com/77928665/154809965-e74783e3-3f2a-484b-a81c-24692c3d8b3f.png)

**Comment by frankTheTank72** [comment]
The idea is that we but the explorer more into the footer like on signum.network - and it is more a general link - you can alwaysd access all items via the explorer by clicking on the links ?!

**Comment by rever273** [comment]
No, I mean explore page, not signum explorer. My bad.
https://signum-art-git-development-signum-network.vercel.app/explore

**Comment by frankTheTank72** [comment]
oh f... we have that 

![grafik](https://user-images.githubusercontent.com/39116221/154811636-028eca81-5d18-4d98-bb5b-f0b2d64177e5.png)

**Comment by frankTheTank72** [comment]
so what was it that you were not able to see that ?

**Comment by rever273** [comment]
oh, I didn't notice it for 2 days using platform ))) It's not obvious.
May be the better way is create two rectangular buttons like this:
![image](https://user-images.githubusercontent.com/77928665/154812044-e5347b37-840a-4891-b807-8dddb3598c47.png)

**Comment by ohager** [comment]
If you hover with your mouse over the icons a tooltip appears. That should be sufficient.

**Comment by rever273** [comment]
@ohager I understand what you mean. But I don't know any marketplaces who hide such important info to icon.
![image](https://user-images.githubusercontent.com/77928665/154813533-f066da6f-bc49-469c-8f5c-b0702d8085b1.png)

You will still be adding server stats in the future (I hope) and another label will appear. Why not make it all clear at once. People have been using header text for 30 years.

**Comment by frankTheTank72** [comment]
pls check i think we can close
