### ISSUE TITLE
Auction function: manually stop it

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#21]
Manually stop the auction by author when he thinks he is satisfied with the current offer. For example, the author set the auction for 1 month, but after a couple of days he realized that the price suits him and he is ready to close it. He don't want to wait so long.
![image](https://user-images.githubusercontent.com/77928665/154815996-3c0592d6-8379-473a-9ac9-0980c96b71f9.png)

**Comment by frankTheTank72** [comment]
The amount is already with him ... so maybe just doing shoter auction could help here too.
Starting an auction cost 0.3 Signa - i think this is okay

**Comment by rever273** [comment]
Yes.
Stop auction if there no bid.
Reduce auction time if owner want it.
