### ISSUE TITLE
Auction function: Max offer price

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#22]
Assign authors the maximum price when opening an auction that they are willing to accept. For example, the author puts the minimum price of the auction at 1000 signa, and he also sets the maximum price at 50,000 signa. The auction ends automatically as soon as someone offer a price of 50,000 or more. This price is visible to all users and the one who likes the NFT the most will be able to buy at the highest price immediately

Something like this:
![image](https://user-images.githubusercontent.com/77928665/154816156-e969ab0c-8cf0-48d7-8b39-7ca8548272b2.png)

**Comment by frankTheTank72** [comment]
So like Ebay "buy now"

**Comment by rever273** [comment]
Yes. But it is an optional parameter. The author can set it to 0 and then the auction will have no ceiling. Or set a very high value, for which the buyer can get the nft immediately and not wait for the end of the auction.
This feature is needed for very rich buyers who don't want to wait and for the author to earn as much as he can.
Again, this option does not have to be set for the author, only if desired.

**Comment by frankTheTank72** [comment]
we will introduce this

**Comment by frankTheTank72** [comment]
added
