### ISSUE TITLE
Clickable Links In NFT descriptions

### ISSUE THREAD

**Issue by Nivok-Spilkommen** [signum-nft/feedback#23]
Can we do that?  Would be nice if links worked in the descriptions, see here:

https://signum-art-git-development-signum-network.vercel.app/item/934676444767340216

**Comment by frankTheTank72** [comment]
For that we have the links on the collection

![grafik](https://user-images.githubusercontent.com/39116221/154839217-97732774-b185-4394-bf76-e936376e5bce.png)

**Comment by Nivok-Spilkommen** [comment]
Not what I'm asking, I want urls in the description for individual NFTs to be 'live'

**Comment by frankTheTank72** [comment]
We will have this with unlockable content - we do not add this on the NFTs direct
