### ISSUE TITLE
Auction: Ability to change the time.

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#24]
_(Just some thoughts for discussion)_

There may be cases where the author made a mistake and set the wrong time for the auction and has to wait very long for the auction to end. 
You could add the ability for the author to manually change the time of the auction at least once. And the change of time should be only in the direction of decreasing, not increasing.
Example: The author set the time 2 months by mistake, he is not ready to wait so long and reduces the time to 2 days.

Also, the author should have the opportunity to remove the NFT from the auction, if there were no bids. So he can start a new auction, or set a fixed price.

**Comment by frankTheTank72** [comment]
As long as no bids are on the auction you an stop it

**Comment by rever273** [comment]
Not now
![image](https://user-images.githubusercontent.com/77928665/154854479-7fcfdd6c-b785-4086-80f3-72f201e55f2e.png)

**Comment by frankTheTank72** [comment]
yes this is currently in development - will be added the next days

**Comment by frankTheTank72** [comment]
You can change the auction as long you have no bids on it

![grafik](https://user-images.githubusercontent.com/39116221/155081589-b1cae699-03e4-467e-9a0a-8ef24285a395.png)

**Comment by rever273** [comment]
Yes, but the problem remains. If there is already a Bid price, and the author has set the time of the auction a few months. There should also be an option to adjust or notify the author... 
For example, when setting the duration of the auction for more than 3 weeks to give a pop-up message: "are you sure you need so much time?"

**Comment by frankTheTank72** [comment]
the last comment will nit be fixed right now - nict to have , so i close the ticket
