### ISSUE TITLE
Incorrect floor price

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#25]
I have only one NFT on sale right now with 17000 Signa. But floor price is 10 Signa.
![image](https://user-images.githubusercontent.com/77928665/154855716-83eb8173-85eb-48cc-af30-d2ceb89fb581.png)

https://signum-art-git-development-signum-network.vercel.app/collection/148518888856685322

**Comment by frankTheTank72** [comment]
we are checking this - looks like only your collection is hit by this bug

**Comment by frankTheTank72** [comment]
should be okay now
