### ISSUE TITLE
Suggestion: Always write collection info

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#26]
If i made NFT in collection, marketplace shows it:
![image](https://user-images.githubusercontent.com/77928665/154864458-c55d3a79-9627-43dd-a5e9-c068000adf35.png)

But when user post NFT without collection it hard to understand where is his collection:
![image](https://user-images.githubusercontent.com/77928665/154864486-b789450e-22e5-4959-a3f9-832c831d5f49.png)

I suggest always writing the Collection, even if the NFT is not part of it.
![image](https://user-images.githubusercontent.com/77928665/154864555-2372a54f-b011-40b4-84e2-a4418956340e.png)

**Comment by frankTheTank72** [comment]
will be added

**Comment by frankTheTank72** [comment]
is added please check
