### ISSUE TITLE
Invalid attribute percentage

### ISSUE THREAD

**Issue by SignumDreadful** [signum-nft/feedback#29]
I have 2 attributes:
- Background
- Character.
The character will be available only after the marketplace test. Each one says "on Mainnet", the characteristics of all 9 tokens are the same, which means that% should be 100%, but writes 50
![incorrect2](https://user-images.githubusercontent.com/100347520/155499498-ce5d5978-5e9a-4588-b8a9-6edbae358083.PNG)
%

**Comment by frankTheTank72** [comment]
We fixed it now - you can check it please

![grafik](https://user-images.githubusercontent.com/39116221/163864080-8f803340-3772-4f92-bf19-0765c4c7ca16.png)
