### ISSUE TITLE
Minted NFT shows up but there is no Pic

### ISSUE THREAD

**Issue by paulpoco** [signum-nft/feedback#3]
**Describe the bug**
Minted NFT shows up but there is no Pic

**Expected behavior**

**Screenshots**
https://signum-art-git-development-signum-network.vercel.app/item/15686508943643699896
![image](https://user-images.githubusercontent.com/801414/154613369-1026098b-a89d-4adc-bfa7-aabd302f07a0.png)

**Additional context**

**Comment by paulpoco** [comment]
Not my NFT but the Bearcoin in the Pic above finally shows.

Mine on the right is flashing.

**Comment by ipr0310** [comment]
@frankTheTank72 Can close the issue now as it is the same as #2

**Comment by frankTheTank72** [comment]
Do you still have the problems? @paulpoco

**Comment by paulpoco** [comment]
Fixed now, sorry I didn't reply sooner
