### ISSUE TITLE
Thumbnail image of NFT makes the image have jagged edges

### ISSUE THREAD

**Issue by paulpoco** [signum-nft/feedback#33]
**Describe the bug**
Thumbnail image of NFT makes the image have jagged edges on the Explore page.

**Screenshots**
![image](https://user-images.githubusercontent.com/801414/155744100-1fedd8e5-bf29-4648-a50c-ff1ae448caaf.png)

**Additional context**
On Desktop and Mobile 
https://signumart.io/item/7338534942017969605

**Comment by frankTheTank72** [comment]
should be okay now - can you check and close if okay pls
