### ISSUE TITLE
On Mobile - the Collections button is missing from the hamburger menu

### ISSUE THREAD

**Issue by paulpoco** [signum-nft/feedback#34]
**Describe the bug**
On Mobile - the Collections button is missing from the hamburger menu

**Screenshots**
![image](https://user-images.githubusercontent.com/801414/155745392-5afe3cf4-276f-438a-a111-e5e6cde7b6f6.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]   Samsung Note 10+
 - OS: [e.g. iOS8.1] Android 12
 - Browser [e.g. stock browser, safari] Chrome 
 - Version [e.g. 22]  98.0.4758.101

**Additional context**

**Comment by ipr0310** [comment]
@paulpoco Collection link is added, you can close this issue!

**Comment by frankTheTank72** [comment]
solved
