### ISSUE TITLE
Can't create auction for new NFT

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#35]
I got the message: An unknown error occured. Please try again or report it

![image](https://user-images.githubusercontent.com/77928665/157398467-0f8bc147-a9b5-45b8-9c21-927429b7f7bc.png)

**Comment by frankTheTank72** [comment]
this is related to the new XT - will be covered with https://github.com/signum-network/signum-xt-wallet/issues/24

**Comment by frankTheTank72** [comment]
i close this ticket
