### ISSUE TITLE
Feature collection: The background does not cover the image of the collection

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#36]
Object has square image, square background and description. 
![image](https://user-images.githubusercontent.com/77928665/160813042-b37134cf-e66d-4c1c-a649-410e131e5ce1.png)

Because the description was added, the background remains rectangular and needs to be expanded to be behind the image.
![unknown](https://user-images.githubusercontent.com/77928665/160813231-f01c769b-4c5c-4ea0-b2dc-0d8e703be66b.png)

**Comment by rever273** [comment]
Also text "Feature collections" is not it this block, this is not a headline, like any other h4 classes. 

You need to change it to <h4 class="MuiTypography-root MuiTypography-h4 MuiTypography-alignCenter css-1l96n2h">Feature collections</h4>

**Comment by frankTheTank72** [comment]
we keep the design right now as it is
