### ISSUE TITLE
Add FAQ/HELP section to header

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#38]
![image](https://user-images.githubusercontent.com/77928665/161918757-1bf2e0ee-47a9-4cc8-b7e5-e76ea0dc19da.png)

And delete it from here:
![image](https://user-images.githubusercontent.com/77928665/161918688-8d0b1983-ce48-4e00-8113-ed3a70c56070.png)

People need to understand how connect Pinata, how add wallet etc. Better with pictures

**Comment by frankTheTank72** [comment]
Links are set ; more in the footer now

![grafik](https://user-images.githubusercontent.com/39116221/163692536-55588139-d890-4ddd-8fbe-52dca8d91775.png)
