### ISSUE TITLE
Delete "Buy now" price after end of auction

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#39]
![image](https://user-images.githubusercontent.com/77928665/161967816-606dc816-925b-4405-9baf-81064194f1ee.png)

Auction ended. No one bought it, but Buy now price remains on NFT image.

**Comment by frankTheTank72** [comment]
we made a fix for that - new auction should handle that correct

**Comment by rever273** [comment]
Yes, working correctly

**Comment by rever273** [comment]
@frankTheTank72 no, don't work correctly.
I made auction for 1 hour with Buy now price 20000. After auction ended - label disappear, all ok.
But after I set fix price to the NFT, and label here again
![image](https://user-images.githubusercontent.com/77928665/162392092-51937849-7421-4eb8-bf53-00fe4e4f8f04.png)
