### ISSUE TITLE
NFT with price 1 Signa wasn't bought

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#40]
I want to buy NFT for 1 Signa. At purchase, a message appeared that I had bought this nft. I paid the price+commission, but the owner did not change.

Link for the NFT:
https://signum-art-git-development-signum-network.vercel.app/item/14160474806606102097

![image](https://user-images.githubusercontent.com/77928665/161968537-0890065e-608e-4db7-bf92-b9ece43a4812.png)

Another nft at 16 Signa price was purchased successfully.

**Comment by frankTheTank72** [comment]
solved

**Comment by rever273** [comment]
@frankTheTank72 
It's didn't solve. Yes, I can press buy button and confirm this in TX wallet. But the transaction is not in the history and I can not get this NFT. This is the second time I tried it today.

Try to buy it yourself

**Comment by frankTheTank72** [comment]
Yes okay we found it  - you already bought the NFT but something went wrong to show it in the Front-End - we fix that
