### ISSUE TITLE
Proposal: Add a view counter. As well as the likes in explore

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#41]
One of marketplace have likes and view counter on explore page, I think it's look good and also can help people to recognize which NFTs are more popular.
![image](https://user-images.githubusercontent.com/77928665/163496668-cb655fe1-bca3-4214-978d-fa00992602f2.png)

I suggest add counter at NFT info section:
![image](https://user-images.githubusercontent.com/77928665/163496952-9fc378a7-54b0-4c6d-ae99-3b0de3f0ea6d.png)

And also at explore:
![image](https://user-images.githubusercontent.com/77928665/163497218-b22efa2b-58ac-489b-8672-ebb702b421c7.png)

This will help the user understand which NFTs are in demand right now, and decide right away to support the author with a like.

**Comment by frankTheTank72** [comment]
we will do that

**Comment by frankTheTank72** [comment]
added 
![grafik](https://user-images.githubusercontent.com/39116221/163692300-885b76f4-bf2b-414c-ab8b-f52158e6b941.png)

**Comment by frankTheTank72** [comment]
Views maybe later - i close the ticket
