### ISSUE TITLE
Only 10 collections are displayed when sorting

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#42]
Now we have 11 collections.

By default there is 11 of them:
https://test.signumart.io/collection/all?sortBy=Date&sortDirection=Desc
![image](https://user-images.githubusercontent.com/77928665/163582659-2de39344-d2fc-425e-8c96-e2045ebe9bff.png)

But if you sort by Oldest or Volume, the are only 10 collections:
https://test.signumart.io/collection/all?sortBy=Date&sortDirection=Asc
![image](https://user-images.githubusercontent.com/77928665/163582719-d5ec2baf-76b3-4730-9351-d2ee26265990.png)

**Comment by frankTheTank72** [comment]
We found the issue - will be fixed soon

**Comment by frankTheTank72** [comment]
fixed
