### ISSUE TITLE
Prohibit a user from placing multiple likes

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#44]
I gave one "Like" to the NFT I created. On the next block, I liked it again. In the end, I gave myself 2 likes. This is wrong. 
Need to make a check that this wallet address can only set 1 likes per 1 NFT and no more. Otherwise users will abuse it.
Here's an example with 2 my likes:

![image](https://user-images.githubusercontent.com/77928665/164125344-a2a19622-c256-46f0-a423-171bed5c3e8b.png)

https://test.signumart.io/item/15339078352753499395

**Comment by frankTheTank72** [comment]
Yes we are aware of it - as you need to pay a network fee  the tx will not stopped.
If we see it used in a way we don´t wanted we can make a block via the front-end - but as MVP we do not implement this
