### ISSUE TITLE
Premature Auction Expiration

### ISSUE THREAD

**Issue by Nivok-Spilkommen** [signum-nft/feedback#6]
Created this NFT https://signum-art-git-development-signum-network.vercel.app/item/5279496835744516871  about 30 mins ago, set 7 day auction, site reports the auction has expired already.

**Comment by ohager** [comment]
There's a known issue with auciton - I'm working on it, rn. Thanks fro reporting

**Comment by rever273** [comment]
It is necessary to add the possibility, if the auction is over and no one has bought NFT, so that the user can organize an auction again, or put the NFT at a fixed price

**Comment by frankTheTank72** [comment]
Issue is fixed - i close the ticket
