### ISSUE TITLE
Add opportunity to set Bid price

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#7]
On other marketplaces, users have the option to set the Bid price at which they would like to buy the NFT if they don't like the author's price. 
We should add the ability for users to offer their own price, and let the author decide for himself whether he is willing to accept it or not.

**Comment by frankTheTank72** [comment]
how  should it work ? - do you send already the amount to the NFT ? or do oyu would excpect a new price at your level as you proposed - and you or somebody else could buy it ?

**Comment by rever273** [comment]
@frankTheTank72 I'm a buyer. I see the NFT, I like it, but I don't want to buy it at that price. Then I make an offer to the author by clicking the "Make an offer" button, where they indicate the price at which I would be willing to buy the nft. 
The author's price appears next to this nft, as well as the bid price. This bid price can be raised by any other user. The author sees the price and decides for himself whether he is ready to sell the nft at it or not.
Example: 
![image](https://user-images.githubusercontent.com/77928665/154733343-85a00327-9984-4e81-ad12-d76c13b86306.png)

**Comment by frankTheTank72** [comment]
as we have the transaction message we could let you write a message to the smart contract which will be attached to the NFT under Event Histroy 

![grafik](https://user-images.githubusercontent.com/39116221/154743124-23b34c13-b039-40bb-a3df-80e5f70b86a7.png)

The message wil be formed as a JSON and your proposal will be shown here

**Comment by rever273** [comment]
Here how it like like on Magic Eden  (Solana)
![image](https://user-images.githubusercontent.com/77928665/154746813-46a1ef0d-d9cf-4472-9480-2d0dfee37c30.png)
A person does not need to write a personal message to the author. He just makes his offer and it is displayed on the NFT, and the author immediately sees it.
The same thing (Bid offer) is in Solanaart Marketplace. It is very convenient and I think you need to think about this functionality.
Each NFTs on Magic Eden/Solana Art etc. have this button. 
![image](https://user-images.githubusercontent.com/77928665/154747222-f207b588-72c6-4312-ae56-7a1d5a132212.png)
Just add "my offer" button.
I hope I tell it clear.

**Comment by frankTheTank72** [comment]
yes understood - but if the author wants to accept the offer - what does he/she need to do ?

**Comment by rever273** [comment]
@frankTheTank72 Just open the NFT link and he can see another button "accept 100 signa price". He can accpt it or just wait another buyer or better offer.

**Comment by rever273** [comment]
As far as I understand, the person who makes the offer sends the coins to the smart contract in advance. And when the author accepts the offer, the coins go to him immediately. If the author refuses the bid price and someone buys from him for another price, then the person who put up the Bid price gets his money back.

**Comment by rever273** [comment]
![image](https://user-images.githubusercontent.com/77928665/154768788-5b457c56-15c1-4e03-8779-7dc52f8c1eb8.png)

oh, you already have "make an offer" button. You just need to activate it and add to NFTs with price.

**Comment by frankTheTank72** [comment]
Yes we have this in general but that is only valid for aucitons - 
I think if we want to make this feature - the one who enter a offer should also be able to remove it - otherwise the coins stay on the contract forever - if the artist is not reacting

**Comment by frankTheTank72** [comment]
added please check - closing the ticket

**Comment by rever273** [comment]
@frankTheTank72 

It seems to work, at least an offer is being made.

I have two suggestions.
**1.** Add offer price to NFT description in explorer. 
Like this:
![image](https://user-images.githubusercontent.com/77928665/162101420-cdcace11-4008-4739-9fff-311a285c06b4.png)

Or like this:
![image](https://user-images.githubusercontent.com/77928665/162101655-135e84b9-e186-4d44-ae3e-89950b0012cb.png)


2. Add those NFTs that the user made an offer for to the My NFT section. Because otherwise the user might just forget which offers he made.
![image](https://user-images.githubusercontent.com/77928665/162101794-c5c6d032-7a66-44a4-9375-58cfd7c73357.png)

**Comment by frankTheTank72** [comment]
we will add a badget - and it should already pop up in the "Shopper" just the badget is missing
