### ISSUE TITLE
rectangle picture issue

### ISSUE THREAD

**Issue by rever273** [signum-nft/feedback#8]
I minted rectangle picture and as you can see there is no border on top and bottom. That's because all preview is square. 
Can you automatically add an image size detection so that the image fits completely into the frame?

![image](https://user-images.githubusercontent.com/77928665/154708360-24113b42-d72a-4e6b-825c-acd243439f18.png)

**Comment by frankTheTank72** [comment]
@rever273 can you add the link to the nft please

**Comment by rever273** [comment]
https://signum-art-git-development-signum-network.vercel.app/item/15212029417968139205

**Comment by frankTheTank72** [comment]
> https://signum-art-git-development-signum-network.vercel.app/item/15212029417968139205

we will check that

**Comment by frankTheTank72** [comment]
this we will keep for layout reasons
