### ISSUE TITLE
Grammar and typo errors in NFT creation confirm message 

### ISSUE THREAD

**Issue by Nivok-Spilkommen** [signum-nft/feedback#9]
'Your NFT is successfully created!
Congratulations! Your NFT is beign tokenized on the Signum blockchain.'

'Your NFT has been...' or 'Your NFT was...'  will apply the correct tense.  'being' misspelled.

Applies to both NFT and collection creation.

**Comment by frankTheTank72** [comment]
will be adjusted

**Comment by frankTheTank72** [comment]
merged into the app
